voting_app/config/routes.rb
VotingApp::Application.routes.draw do

  root 'home#homepage'
  resources :elections do
    collection do
      post :vote
      post :evaluate_election
      post :addParticipants
    end
  end

  devise_for :user

end

voting_app/app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :election
end

voting_app/app/models/election.rb
class Election < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :choices
  accepts_nested_attributes_for :choices, allow_destroy: true

  def addParticipant(participant)
    if participant == nil
      raise ArgumentError, 'invalid user email'
    end
    if participant.id == nil
      raise ArgumentError, 'participant has no id'
    end

    sql = "INSERT INTO elections_users (election_id, user_id)
           VALUES (#{id}, #{participant.id})"
    ActiveRecord::Base.connection.execute(sql)
  end

  def findParticipant(participant_id)
    self.users.find(participant_id)
  end

  def voted?(user_id)
    sql = "SELECT * FROM elections_users
           WHERE election_id = #{self.id}
           AND user_id = #{user_id};"
    result = ActiveRecord::Base.connection.execute(sql)[0]
    result["voted"] != 'f'
  end

  def vote(user_id, vote_choice)
    sql="UPDATE elections_users
          SET voted = 't'
          WHERE user_id = #{user_id}
          AND election_id = #{id};"
    ActiveRecord::Base.connection.execute(sql)
    choice = Choice.find_by(election_id: id, name: vote_choice)
    choice.votes += 1
    choice.save
  end

  def evaluate_election
    winner = 0
    self.choices.each do |choice|
      if choice.votes > winner
        winner = choice.votes
        self.winner_id = choice.id
        self.status = "winner"
      elsif choice.votes == winner
        self.status = "tie"
        self.winner_id = choice.id
      end
    end
    self.save
  end
end

voting_app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #has_many :elections
  has_and_belongs_to_many :elections

  def ownedElections
    Election.where(owner_id: self.id)
  end

  def participatingElections
    self.elections
  end
end

voting_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def set_cache_buster
        response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

voting_app/app/controllers/elections_controller.rb
class ElectionsController < ApplicationController

  def new
    @election = Election.new()
  end

  def show
    @election = Election.find(params[:id])
  end

  def validElection?
    email_array = params[:emails].split(',')
    email_array.each do |email|
      if User.find_by(email: email.strip) == nil
        flash[:notice] = "There is no user with email #{email}"
        return false
      end
    end
    if params[:election][:title] == ""
      flash[:notice] = 'Election requires a title'
      return false
    end
    choices_array = params[:options]
    number_of_choices = 0
    choices_array.each do |index, choice|
      number_of_choices += 1 unless choice == ""
    end
    if !(number_of_choices > 1)
      flash[:notice] = 'Election requires at least two voting choices'
      return false
    end
    return number_of_choices > 1
  end

  def create
    @election = Election.new(election_params)
    if !validElection?
      render 'elections/new'
      return
    end
    if @election.save
      params[:options].each do |index,name|
        Choice.create(election_id: @election.id, name: name)
      end
      owner_email = User.find(@election.owner_id).email
      email_array = params[:emails].split(',')
      email_array << owner_email unless email_array.include?(owner_email)
      email_array.each do |email|
        @election.addParticipant(User.find_by(email: email.strip))
      end

      flash[:notice] = 'Election was created'
      redirect_to @election
    else
      flash[:notice] = 'Error. Election was not created'
      render 'new'
    end
  end

  def evaluate_election
    @election = Election.find(params[:id])
    @election.evaluate_election
    redirect_to @election
  end

  def addParticipants
    @election = Election.find(params[:id])
    emails = params[:emails]
    existing_emails = @election.users.map{|user| user.email}
    emails.split(',').each do |email|
      name = email.strip()
      if !existing_emails.include?(name)
        @election.addParticipant(User.find_by(email: email))
      end
    end
    redirect_to @election
  end

  def vote
    @election = Election.find(params[:election_id])
    flash[:notice] = "You voted for #{params[:elections_controller][:vote]} in the election #{@election.title}"
    @election.vote(params[:user_id], params[:elections_controller][:vote])
    redirect_to root_path
  end
  private

  def userToEmail(user)
    user.email
  end

  def election_params
    params.require(:election).permit(:title, :owner_id)
  end
end

voting_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

voting_app/app/controllers/user_controller.rb
class UserController < ApplicationController
end

voting_app/app/helpers/application_helper.rb
module ApplicationHelper
end

voting_app/app/helpers/election_helper.rb
module ElectionHelper
end

voting_app/app/helpers/home_helper.rb
module HomeHelper
end

voting_app/app/helpers/user_helper.rb
module UserHelper
end

voting_app/app/views/elections/new.html.erb
<%= form_for @election, action: :create do |f| %>
  <%= f.label 'Election name' %>
  <%= f.text_field :title %>
  <label for='mails'>Emails</label>
  <input type='text' name='emails' id='mails' />
  <%= f.hidden_field :owner_id, value: current_user.id %>
  <div>

  </div>
  <h2> Voting Options </h2>
  <ol>
    <li><input type='text' name='options[1]' id='options1'></li>
    <li><input type='text' name='options[2]' id='options2'></li>
  </ol>
  <%= f.submit %>
<% end %>

voting_app/app/views/elections/show.html.erb
<h1>Election: <%= @election.title %></h1>
<% if @election.status == "winner" %>
  <h3><%= Choice.find(@election.winner_id).name %> won! </h3>
<% elsif @election.status == "tie" %>
  <h3> The election was a tie </h3>
<% else %>
  <% if @election.voted?(current_user.id) %>
    <p> You have already voted in this election!</p>
  <% end %>
  <% if !(@election.choices.empty?) %>
    <p>Choices to vote for:<p>
    <ol>
      <%= form_tag(vote_elections_path(action: "vote"), method: 'post') do %>
        <% @election.choices.each do |choice| %>
          <li><%= radio_button :elections_controller, :vote, choice.name, {choice: :choice_id, method: 'post', checked: true} %> <%= choice.name %> </li>
        <% end %>
        <br/>
        <%= hidden_field_tag "election_id", @election.id %>
        <%= hidden_field_tag "user_id", current_user.id %>
        <%= submit_tag "Submit Vote" %>
        <% end %>
    </ol>
  <% end %>
  <% if !(@election.users.empty?) %>
    <p>Voters in election:<p>
    <ol>
    <% @election.users.each do |participant| %>
      <li><%= participant.email %></li>
    <% end %>
    </ol>
  <% end %>
  <% if current_user.id == @election.owner_id %>

    <%= form_tag controller: :elections, action: :addParticipants, method: 'post' do %>
      <label for='mails'>Add new emails</label>
      <input type='text' name='emails' id='mails' />
      <%= hidden_field_tag :id, @election.id %>
      <%= submit_tag 'Update Election'%>
    <% end %>

    <%= link_to 'End election and evaluate results', {controller: :elections, action: :evaluate_election, id: @election.id}, {method: :post} %>
  <% end %>
<% end %>

voting_app/app/views/home/homepage.html.erb
<head>
</head>
<body>
  <h1>Welcome to E-elections!</h1>
  <% if current_user != nil %>
    <% if !current_user.ownedElections.empty?  %>
      <p> Elections that you own: </p>
      <ul>
        <div class='owned'>
          <% current_user.ownedElections.each do |election| %>
            <li><%= link_to election.title, election %></li>
          <% end %>
        </div>
      </ul>
    <% end %>
    <% if !current_user.participatingElections.empty? %>
      <p> Elections that you can vote in: </p>
      <ul>
        <div class= 'participating'>
          <% current_user.participatingElections.each do |election| %>
            <li><%= link_to election.title, election %></li>
          <% end %>
      </div>
      </ul>
    <% end %>
  <% end %>
</body>

voting_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VotingApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%# favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">VotingApp</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
              <% if !user_signed_in? %>
                <li><%= link_to 'Sign In', new_user_session_path %></li>
                <li><%= link_to 'Register', new_user_registration_path %></li>
              <% else %>
                <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                <li><%= link_to 'Create an election', new_election_path %></li>
                <li><%= link_to current_user.email, '#' %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div style='margin-left:25px;'>
      <div style="color:#880088;text-align:center;">
        <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: name %>
        <% end -%>
      </div>
      <%= yield %>
    </div>
       <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

voting_app/app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>